### ISSUE TITLE
build failure: Could not find/install babel plugin 'transform-object-rest-spread'

### ISSUE THREAD

**Issue by Bobgy** [CompuIves/codesandbox-client#1177]
# 🐛 bug report

## Description of the problem
I imported a repo from github created by CRA 2, and it fails to compile in codesandbox with error message: `Could not find/install babel plugin 'transform-object-rest-spread': Cannot find module '@babel/plugin-transform-object-rest-spread' from '/src'`

I tried creating a new repo with template create-react-app in codesandbox and copied my code there, but it failed with the same error too. However, I verified object rest spread syntax is working with codesandbox, so I don't really understand what is going wrong here.

## How has this issue affected you? What are you trying to accomplish?

just trying to import a CRA 2 repo from github and maybe share it as demo

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  latest |
| Browser | Chrome |
| Operating System | macOS |

**Comment by CompuIves** [comment]
Should be fixed with a deploy in 15 min! The isssue was that we run CRA v1 transforms on the jsx files, I fixed that.

**Comment by Bobgy** [comment]
@CompuIves thank you! confirmed it's working now

**Comment by saityro** [comment]
Hello there! I'm having this exact problem today. Same config but on windows 10.
```proxyConsole.js:72 Error: Could not find/install babel plugin 'transform-object-rest-spread': Cannot find module '@babel/plugin-transform-object-rest-spread' from '/src'
    at C (worker-error-handler.js:22)
    at Worker.<anonymous> (worker-transpiler.js:134)
    at g (runtime.js:62)
    at Generator._invoke (runtime.js:296)
    at Generator.e.(/anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.89dc2bd1.chunk.js:1:191326)
    at i (asyncToGenerator.js:12)
    at l (asyncToGenerator.js:27)
    at asyncToGenerator.js:34
    at new Promise (<anonymous>)
    at new o (_export.js:36)
    at Worker.<anonymous> (asyncToGenerator.js:7)
    at Worker.<anonymous> (worker-transpiler.js:129)
function.console.(anonymous function) @ proxyConsole.js:72
(anonymous) @ compile.js:622
g @ runtime.js:62
(anonymous) @ runtime.js:296
e.(anonymous function) @ runtime.js:114
i @ asyncToGenerator.js:12
a @ asyncToGenerator.js:31
Promise.then (async)
i @ asyncToGenerator.js:22
l @ asyncToGenerator.js:27
Promise.then (async)
i @ asyncToGenerator.js:22
l @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
o @ _export.js:36
(anonymous) @ asyncToGenerator.js:7
ie @ compile.js:371
oe @ compile.js:371
(anonymous) @ compile.js:699
g @ runtime.js:62
(anonymous) @ runtime.js:296
e.(anonymous function) @ runtime.js:114
i @ asyncToGenerator.js:12
l @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
o @ _export.js:36
(anonymous) @ asyncToGenerator.js:7
de @ compile.js:694
ue @ compile.js:694
pe @ compile.js:716
(anonymous) @ index.js:128
Promise.then (async)
(anonymous) @ index.js:98
Promise.then (async)
./src/sandbox/index.js @ index.js:40
o @ bootstrap:83
4 @ delay.js:3
o @ bootstrap:83
n @ bootstrap:45
../../node_modules/raw-loader/index.js!./src/sandbox/eval/transpilers/vue/style-loader/addStylesClient.js @ bootstrap:218
(anonymous) @ bootstrap:218
babel-worker.js:95 First time compiling transform-decorators-legacy went wrong, got:
(anonymous) @ babel-worker.js:95
A @ runtime.js:62
(anonymous) @ runtime.js:296
e.(anonymous function) @ runtime.js:114
u @ asyncToGenerator.js:12
a @ asyncToGenerator.js:27
Promise.then (async)
u @ asyncToGenerator.js:22
a @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:7
Me @ babel-worker.js:78
(anonymous) @ babel-worker.js:349
A @ runtime.js:62
(anonymous) @ runtime.js:296
e.(anonymous function) @ runtime.js:114
u @ asyncToGenerator.js:12
a @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:7
(anonymous) @ babel-worker.js:340
(anonymous) @ babel-worker.js:340
A @ runtime.js:62
(anonymous) @ runtime.js:296
e.(anonymous function) @ runtime.js:114
u @ asyncToGenerator.js:12
a @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:7
(anonymous) @ babel-worker.js:213
babel-worker.js:96 Error: Cannot find module 'transform-decorators-legacy' from '/src'
    at Function.e.exports [as sync] (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:347652)
    at Function.c.sync (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:340769)
    at ge (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:375507)
    at https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:378551
    at A (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:314575)
    at Generator._invoke (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:314363)
    at Generator.e.(anonymous function) [as next] (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:314754)
    at u (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:3279)
    at a (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:3368)
(anonymous) @ babel-worker.js:96
A @ runtime.js:62
(anonymous) @ runtime.js:296
e.(anonymous function) @ runtime.js:114
u @ asyncToGenerator.js:12
a @ asyncToGenerator.js:27
Promise.then (async)
u @ asyncToGenerator.js:22
a @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:7
Me @ babel-worker.js:78
(anonymous) @ babel-worker.js:349
A @ runtime.js:62
(anonymous) @ runtime.js:296
e.(anonymous function) @ runtime.js:114
u @ asyncToGenerator.js:12
a @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:7
(anonymous) @ babel-worker.js:340
(anonymous) @ babel-worker.js:340
A @ runtime.js:62
(anonymous) @ runtime.js:296
e.(anonymous function) @ runtime.js:114
u @ asyncToGenerator.js:12
a @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:7
(anonymous) @ babel-worker.js:213
babel-worker.js:95 First time compiling transform-class-properties went wrong, got:
(anonymous) @ babel-worker.js:95
A @ runtime.js:62
(anonymous) @ runtime.js:296
e.(anonymous function) @ runtime.js:114
u @ asyncToGenerator.js:12
a @ asyncToGenerator.js:27
Promise.then (async)
u @ asyncToGenerator.js:22
a @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:7
Me @ babel-worker.js:78
(anonymous) @ babel-worker.js:349
A @ runtime.js:62
(anonymous) @ runtime.js:296
e.(anonymous function) @ runtime.js:114
u @ asyncToGenerator.js:12
a @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:7
(anonymous) @ babel-worker.js:340
(anonymous) @ babel-worker.js:340
A @ runtime.js:62
(anonymous) @ runtime.js:296
e.(anonymous function) @ runtime.js:114
u @ asyncToGenerator.js:12
a @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:7
(anonymous) @ babel-worker.js:213
babel-worker.js:96 Error: Cannot find module 'transform-class-properties' from '/src'
    at Function.e.exports [as sync] (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:347652)
    at Function.c.sync (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:340769)
    at ge (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:375507)
    at https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:378551
    at A (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:314575)
    at Generator._invoke (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:314363)
    at Generator.e.(anonymous function) [as next] (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:314754)
    at u (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:3279)
    at a (https://llkrkx0z47.codesandbox.io/babel-transpiler.03b4e2e1.worker.js:1:3368)```

**Comment by GulcanBaran** [comment]
Hello there, you can use "Add Dependency" button to add babel-plugin-transform-es2015-modules-commonjs in CodeSandBox. It solves the same problem on windows 10.
