### ISSUE TITLE
Debug Failure. False expression: Output generation failed

### ISSUE THREAD

**Issue by Noviny** [CompuIves/codesandbox-client#1535]
# 🐛 bug report

## Description of the problem

In several sandboxes, I have encountered the following error:

```
Error: Debug Failure. False expression: Output generation failed
    at X (https://codesandbox.io/static/js/sandbox.f456e2b7.js:1:109402)

    at Worker.<anonymous> (https://codesandbox.io/static/js/sandbox.f456e2b7.js:1:112385)

    at g (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:11215)

    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:11003)

    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:11394)

    at r (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:702)

    at u (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:912)

    at https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:971

    at new Promise (<anonymous>)

    at Worker.<anonymous> (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:853)

    at Worker.<anonymous> (https://codesandbox.io/static/js/sandbox.f456e2b7.js:1:113565)
```

This occurs from a sandbox that uses codesandboxer-fs to generate the content of the sandbox. I am not sure if it is a codesandboxer error, or how to go about further debugging this.

## How has this issue affected you? What are you trying to accomplish?

Uncertainty about publishing a different .ts fix for codesandboxer-fs.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by Noviny** [comment]
<3 Thanks!
