### ISSUE TITLE
vue jsx not transformed correctly

### ISSUE THREAD

**Issue by darrenjennings** [CompuIves/codesandbox-client#431]
`babel-plugin-transform-vue-jsx` converts vue jsx to createElement using `h`. It appears codesandbox is converting jsx to React.createElement instead of `h`.

Sample codesandbox with error:
https://codesandbox.io/s/q9zm2j1jr9

This is a recent issue as my sandboxes were functional a few days ago.

```
[Vue warn]: Error in render: "ReferenceError: React is not defined"

found in

---> <Mouse>
       <App> at /App.vue
         <Root>
ReferenceError: React is not defined
    at VueComponent.__render (https://q9zm2j1jr9.codesandbox.io/App.vue?6d26d5ad:23:7)
    at Proxy.boundFn (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:188:14)
    at Proxy.render (https://q9zm2j1jr9.codesandbox.io/Mouse.js:34:13)
    at VueComponent.Vue._render (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:4392:22)
    at VueComponent.updateComponent (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:2692:21)
    at Watcher.get (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:3035:25)
    at new Watcher (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:3024:12)
    at mountComponent (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:2696:17)
    at VueComponent.Vue$3.$mount (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:8228:10)
    at VueComponent.Vue$3.$mount (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:10542:16)
    at init (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:3988:13)
    at createComponent (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:5427:9)
    at createElm (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:5363:9)
    at createChildren (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:5498:9)
    at createElm (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:5403:9)
    at VueComponent.patch [as __patch__] (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:5881:7)
    at VueComponent.Vue._update (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:2564:19)
    at VueComponent.updateComponent (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:2692:10)
    at Watcher.get (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:3035:25)
    at new Watcher (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:3024:12)
    at mountComponent (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:2696:17)
    at VueComponent.Vue$3.$mount (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:8228:10)
    at VueComponent.Vue$3.$mount (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:10542:16)
    at init (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:3988:13)
    at createComponent (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:5427:9)
    at createElm (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:5363:9)
    at Vue$3.patch [as __patch__] (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:5917:9)
    at Vue$3.Vue._update (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:2564:19)
    at Vue$3.updateComponent (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:2692:10)
    at Watcher.get (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:3035:25)
    at new Watcher (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:3024:12)
    at mountComponent (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:2696:17)
    at Vue$3.$mount (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:8228:10)
    at Vue$3.$mount (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:10542:16)
    at Vue$3.Vue._init (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:4488:10)
    at new Vue$3 (https://q9zm2j1jr9.codesandbox.io/node_modules/vue/dist/vue.common.js:4573:8)
    at evaluate (https://q9zm2j1jr9.codesandbox.io/index.js:18:1)
    at r.a (https://q9zm2j1jr9.codesandbox.io/static/js/sandbox.9037e7ee.js:3868:494)
    at e.value (https://q9zm2j1jr9.codesandbox.io/static/js/sandbox.9037e7ee.js:3923:452)
    at e.value (https://q9zm2j1jr9.codesandbox.io/static/js/sandbox.9037e7ee.js:3895:6943)
    at e.value (https://q9zm2j1jr9.codesandbox.io/static/js/sandbox.9037e7ee.js:3895:6743)
    at https://q9zm2j1jr9.codesandbox.io/static/js/sandbox.9037e7ee.js:2537:2837
    at t (https://q9zm2j1jr9.codesandbox.io/static/js/common-sandbox.c5930ce2.js:1933:811)
    at Generator._invoke (https://q9zm2j1jr9.codesandbox.io/static/js/common-sandbox.c5930ce2.js:1933:599)
    at Generator.e.(anonymous function) [as next] (https://q9zm2j1jr9.codesandbox.io/static/js/common-sandbox.c5930ce2.js:1933:990)
    at n (https://q9zm2j1jr9.codesandbox.io/static/js/common-sandbox.c5930ce2.js:2117:316)
    at https://q9zm2j1jr9.codesandbox.io/static/js/common-sandbox.c5930ce2.js:2117:412
    at <anonymous>
```

**Comment by CompuIves** [comment]
Thanks for letting me know! Will write a fix now...

**Comment by CompuIves** [comment]
Fixed with https://github.com/CompuIves/codesandbox-client/commit/e573a4cbf6a496c0e56633c0a82e8d78e92434a8, will deploy now...

**Comment by CompuIves** [comment]
Deployed and fixed!
