### ISSUE TITLE
Cannot read property 'instantiate' of undefined

### ISSUE THREAD

**Issue by rajjejosefsson** [CompuIves/codesandbox-client#505]
Can't go to my sandbox https://codesandbox.io/s/612l1j41vr

Chrome version: Version 64.0.3282.140 (Official Build) (64-bit)

Getting following error:

```
raven.js:422 Uncaught TypeError: Cannot read property 'instantiate' of undefined
    at t.instantiate (https://codesandbox.io/static/js/app.50cac457.js:2202:44323)
    at https://codesandbox.io/static/js/app.50cac457.js:2202:35637
    at https://codesandbox.io/static/js/app.50cac457.js:2202:41030
    at Array.forEach (<anonymous>)
    at t.forAllProps (https://codesandbox.io/static/js/app.50cac457.js:2202:41003)
    at n.finalizeNewInstance (https://codesandbox.io/static/js/app.50cac457.js:2202:35543)
    at new e (https://codesandbox.io/static/js/app.50cac457.js:2202:17562)
    at X (https://codesandbox.io/static/js/app.50cac457.js:2202:7159)
    at t.instantiate (https://codesandbox.io/static/js/app.50cac457.js:2202:39283)
    at t.willChange (https://codesandbox.io/static/js/app.50cac457.js:2202:30688)
    at Array.<anonymous> (https://codesandbox.io/static/js/app.50cac457.js:2202:29876)
    at s (https://codesandbox.io/static/js/common.0cdac3cc.js:420:502)
    at e.set (https://codesandbox.io/static/js/common.0cdac3cc.js:434:22868)
    at https://codesandbox.io/static/js/app.50cac457.js:49:3063
    at https://codesandbox.io/static/js/app.50cac457.js:49:2098
    at Array.reduce (<anonymous>)
    at https://codesandbox.io/static/js/app.50cac457.js:49:2007
    at runInBatch (https://codesandbox.io/static/js/app.50cac457.js:49:1486)
    at O (https://codesandbox.io/static/js/common.0cdac3cc.js:420:2409)
    at n (https://codesandbox.io/static/js/common.0cdac3cc.js:420:2013)
    at https://codesandbox.io/static/js/app.50cac457.js:2202:5171
    at B (https://codesandbox.io/static/js/app.50cac457.js:2202:5210)
    at Object.<anonymous> (https://codesandbox.io/static/js/app.50cac457.js:2202:5306)
    at t.value (https://codesandbox.io/static/js/app.50cac457.js:49:1983)
    at t.value (https://codesandbox.io/static/js/app.50cac457.js:49:3005)
    at ProviderConstructor.e.(anonymous function) [as set] (https://codesandbox.io/static/js/app.50cac457.js:459:565)
    at Object.n [as function] (https://codesandbox.io/static/js/app.50cac457.js:4000:13828)
    at e.value (https://codesandbox.io/static/js/app.50cac457.js:731:13561)
    at u (https://codesandbox.io/static/js/app.50cac457.js:731:18344)
    at https://codesandbox.io/static/js/app.50cac457.js:731:17870
    at https://codesandbox.io/static/js/app.50cac457.js:731:13742
    at <anonymous>
```

**Comment by CompuIves** [comment]
Hey @rajjejosefsson, thanks for noticing us, we're looking into it!

**Comment by CompuIves** [comment]
Pushed a fix just now, will be live in 5 min!

**Comment by tsaiDavid** [comment]
@CompuIves - Patron here, keep up the awesome work! I'm actually still seeing this same issue. Does this have anything to do with public, unlisted, private settings?

PS - on the same note, is there any way to run private repos from Github?

**Comment by CompuIves** [comment]
Hmm, I think you have the right hunch @tsaiDavid. I'll check on dev now.

**Comment by CompuIves** [comment]
I think I found this issue! Should be live in 10 minutes.

Regarding your other question:

We don't support importing private repos yet, I think this is a good feature to add though since we now support committing as well. Would you be interested in opening an issue for it?
