### ISSUE TITLE
Jest in CodeSandbox 3.0

### ISSUE THREAD

**Issue by gautamarora** [CompuIves/codesandbox-client#513]
Creating an issue to discuss future features for Jest integration in CodeSandbox...

Jest in 2.5 - [issue](https://github.com/CompuIves/codesandbox-client/issues/364) | [release](https://hackernoon.com/announcing-codesandbox-2-5-be767d15ffd)
- [x] Unit testing
- [x] Mock functions
- [x] Snapshot testing (read only, does not create new snapshots)

Jest in CodeSandbox 3
- [ ] Snapshot saving
- [ ] Manual mocks
- [ ] Jest config

Please comment in this issue with more features that should be added to the list.

cc @CompuIves

**Comment by gautamarora** [comment]
also cc @gillchristian - interested to help with code or ideas? :)

**Comment by gillchristian** [comment]
Yeah, I just joined Discord, we can talk there :smile:

**Comment by alexilyaev** [comment]
`jest.config.js` support would be really nice.

**Comment by gillchristian** [comment]
@alexilyaev indeed, in the [Discord](https://discordapp.com/channels/333980639973867521) I mentioned I'd like to work on it but haven't found the time yet :grimacing:

**Comment by rdiazv** [comment]
Fake timers 🙏

`jest.useFakeTimers is not a function`

**Comment by Pyrolistical** [comment]
Would have been nicer when I called `jest.mock(..)` instead of getting `TypeError: jest.mock is not a function`, I would get a `Error: not implemented yet in codesandbox.io, see: https://github.com/CompuIves/codesandbox-client/issues/513`

**Comment by codialsoftware** [comment]
or `jest.doMock` ;)
I've look through half of half of the Internet to finally find this bug :D

**Comment by jdhines** [comment]
> Would have been nicer when I called `jest.mock(..)` instead of getting `TypeError: jest.mock is not a function`, I would get a `Error: not implemented yet in codesandbox.io, see: https://github.com/CompuIves/codesandbox-client/issues/513`

+1 As local code works fine, the "not a function" error is a bit misleading (to me anyways), as I literally found out about CodeSandbox today (super awesome BTW!) and trying to use it to [testdrive](https://codesandbox.io/s/p51k27717q) react components and jest tests.

**Comment by iDVB** [comment]
So I've read this thread over 3x and still not sure if this is still an known issue or not.
I continue to get the error...
`jest.mock is not a function

There seems to be codesandbox docs about using Jest... but no mention of limitations.
https://codesandbox.io/docs/tests

**Comment by dwiyatci** [comment]
@iDVB I don't think `jest.mock()`/"automatic mock"  is supported yet. 🤔 

How do we check the version of CodeSandbox from the dashboard btw?

**Comment by SaraVieira** [comment]
@dwiyatci You can check the version in any sandbox here:

![screenshot 2019-02-20 at 10 17 51](https://user-images.githubusercontent.com/1051509/53080382-d9ac6b00-34f8-11e9-8d67-8070cba7072c.png)

**Comment by dwiyatci** [comment]
@SaraVieira Thank you. :) But what I meant was: how can we tell whether it's CodeSandbox 2.5 or 3.0? :sweat_smile:

**Comment by SaraVieira** [comment]
Shhhhhit, no idea haha

Ask Ives 🤔

@compuives

**Comment by mohsinulhaq** [comment]
`jest.useFakeTimers is not a function`
Hi, is there any update for above fix?

**Comment by lbogdan** [comment]
@gautamarora , @gillchristian Are you guys still interested in pursuing this?

**Comment by karlhorky** [comment]
I'd be interested in having the Snapshot Saving feature if possible!

Or is it possible already? 

For example, I was thinking about the potential of the **Run any NPM Script** feature [CodeSandbox Containers](https://hackernoon.com/codesandbox-containers-5864a8f26715), which seems to enable running Jest with the `-u` flag via an npm script...

**Comment by karlhorky** [comment]
@SaraVieira just confirmed my suspicions that this is only possible at the moment with Containers.

Is CodeSandbox satisfied with this? Or would you also like to be able to create and update files on non-Container sandboxes? (maybe a whitelisted list of things that can be updated, at least to start with?)

**Comment by karlhorky** [comment]
Also Manual Mocks - those would be super useful.

At the moment, the closest thing that I've found is to use the `import * as name from '../relative/path'` syntax with mock functions, but that only seems to work for local modules, not dependencies...

```js
import { useIt } from "./use-default-export";

import * as myfunc from "./default-export-function";

test("use-default-export-function", () => {
  expect(useIt()).toEqual("real");
});

test("use-default-export-function with mock", () => {
  myfunc.default = jest.fn(() => "unreal");
  expect(useIt()).toEqual("unreal");
});
```

https://codesandbox.io/s/88wlzp6q88

**Comment by sag1v** [comment]
People who came here because this error or similar (like me)
> jest.useFakeTimers is not a function

For now you can bypass this issue and use the `done()` callback of `jest`

```
it("uses a timer", done => {
  console.log("start");
  let x = 0;
  setTimeout(() => {
    console.log("done!");
    expect(x === 0).toBe(true);
    done();
  }, 250);
  console.log("continue");
});
```

**Comment by rakeshshubhu** [comment]
is this still an issue? I'm getting the same error from 2018 on jest.mock

**Comment by stephanepericat** [comment]
is this fixed yet ?

**Comment by rakeshshubhu** [comment]
@stephanepericat i dont think so.. its since 2018

**Comment by gugol2** [comment]
Still is not jest.mock available in CodeSandbox?

I just tried..., what a pity!

**Comment by sag1v** [comment]
@gugol2 It is in the [readme](https://github.com/sag1v/react-elastic-carousel#note).

Though i just found out its not updated in NPM :/
I will update it thanks

**Comment by rollrodrig** [comment]
september 2020, `jest.mock` and `jest.useFakeTimers` are still bugs.

**Comment by Sayvai** [comment]
I opened a GitHub Discussions chat (#5042) on this. 

Feel free to comment over there too.

Hopefully it will help further gain traction for serious consideration to add Jest mocks support, alongside this open issue.

**Comment by mrdulin** [comment]
Hit this issue today, codesandbox: https://codesandbox.io/s/crimson-framework-jddh2?file=/src/index.test.js

There was an error while evaluating the file:
> jest.useFakeTimers is not a function

**Comment by aleks-rope** [comment]
> jest.useFakeTimers is not a function

Issue still persists. Just checked today.

**Comment by lucksp** [comment]
jest.mock is not a function still an error.

**Comment by ardnahcivar** [comment]
`jest.useFakeTimers is not a function`  still persists
https://codesandbox.io/s/fancy-morning-lmwx6?file=/src/index.test.ts

**Comment by moogus** [comment]
guess this is still a problem 😔

**Comment by agallio** [comment]
Still got this error when running tests.
https://codesandbox.io/s/github/kentcdodds/react-testing-library-examples/tree/main/?from-embed&initialpath=%2F__tests__%2Fasync.js

```
jest.useRealTimers is not a function

TypeError: jest.useRealTimers is not a function
    at runWithJestRealTimers (https://vj929.csb.app/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:651:8)
    at runWithRealTimers (https://vj929.csb.app/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:634:12)
    at Window.evaluate (https://vj929.csb.app/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:682:26)
    at z (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:99284)
    at G.evaluate (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:111641)
    at be.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:121458)
    at c (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:111387)
    at Window.evaluate (https://vj929.csb.app/node_modules/@testing-library/react/dist/@testing-library/react.esm.js:44:17)
    at z (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:99284)
    at G.evaluate (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:111641)
    at be.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:121458)
    at c (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:111387)
    at Window.evaluate (https://vj929.csb.app/src/__tests__/react-lazy-and-suspense.js:13:15)
    at z (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:99284)
    at G.evaluate (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:111641)
    at be.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:121458)
    at be.evaluateModule (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:120957)
    at https://codesandbox.io/static/js/7.4b9a6a838.chunk.js:1:15776
    at l (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257422)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257175)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257779)
    at t (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2420)
    at i (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2631)
    at https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2690
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2571
    at https://codesandbox.io/static/js/7.4b9a6a838.chunk.js:1:16135
    at Array.map (<anonymous>)
    at e.<anonymous> (https://codesandbox.io/static/js/7.4b9a6a838.chunk.js:1:15477)
    at l (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257422)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257175)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257779)
    at t (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2420)
    at i (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2631)
```

**Comment by dhatGuy** [comment]
> Still got this error when running tests.
> https://codesandbox.io/s/github/kentcdodds/react-testing-library-examples/tree/main/?from-embed&initialpath=%2F__tests__%2Fasync.js
> 
> ```
> jest.useRealTimers is not a function
> 
> TypeError: jest.useRealTimers is not a function
>     at runWithJestRealTimers (https://vj929.csb.app/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:651:8)
>     at runWithRealTimers (https://vj929.csb.app/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:634:12)
>     at Window.evaluate (https://vj929.csb.app/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:682:26)
>     at z (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:99284)
>     at G.evaluate (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:111641)
>     at be.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:121458)
>     at c (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:111387)
>     at Window.evaluate (https://vj929.csb.app/node_modules/@testing-library/react/dist/@testing-library/react.esm.js:44:17)
>     at z (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:99284)
>     at G.evaluate (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:111641)
>     at be.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:121458)
>     at c (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:111387)
>     at Window.evaluate (https://vj929.csb.app/src/__tests__/react-lazy-and-suspense.js:13:15)
>     at z (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:99284)
>     at G.evaluate (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:111641)
>     at be.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:121458)
>     at be.evaluateModule (https://codesandbox.io/static/js/sandbox.3fb0c3bb6.js:1:120957)
>     at https://codesandbox.io/static/js/7.4b9a6a838.chunk.js:1:15776
>     at l (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257422)
>     at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257175)
>     at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257779)
>     at t (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2420)
>     at i (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2631)
>     at https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2690
>     at new Promise (<anonymous>)
>     at https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2571
>     at https://codesandbox.io/static/js/7.4b9a6a838.chunk.js:1:16135
>     at Array.map (<anonymous>)
>     at e.<anonymous> (https://codesandbox.io/static/js/7.4b9a6a838.chunk.js:1:15477)
>     at l (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257422)
>     at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257175)
>     at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:257779)
>     at t (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2420)
>     at i (https://codesandbox.io/static/js/common-sandbox.51de09afd.chunk.js:1:2631)
> ```

Facing the same issue too

**Comment by KrustyC** [comment]
Hi here, I get the same issue as well https://codesandbox.io/s/modern-morning-md378

Do we have any update on this?

**Comment by wwwmonkey** [comment]
Apologies if cross-posting issue, but appreciate any work-around or ideas for my issue regarding Jest not working on Static templates.

https://github.com/codesandbox/codesandbox-client/issues/5726

**Comment by CompuIves** [comment]
Yes, this is still something we want to do, but it's challenging. It's something that we haven't planned in the near-future, but we do want to expand the Jest functionality in the future. I can't tell when we'll have this though.

**Comment by nickmccurdy** [comment]
It seems like this is still being worked on.

**Comment by NS-BOBBY-C** [comment]
I'm looking into this one and I have some questions about the jest implementation.

Normally, when the Jest global is initialized its created by the jest-runtime and mock/other timer functions are added to the global Jest object. [This can be seen here.](https://github.com/facebook/jest/blob/46c9c13811ca20a887e2826c03852f2ccdebda7a/packages/jest-runtime/src/index.ts#L1814-1900) 

What's happening in codesandbox is that the jest-runtime is never being initialized - I presume there may be some reason for this. That can be seen here, where jest is actually initialized [here](https://github.com/NS-BOBBY-C/codesandbox-client/blob/16ace4609a4e46f96ff616e330c382e67c117cb9/packages/app/src/sandbox/eval/tests/jest-lite.ts#L117-L159) with the MockModule class from jest-mock, which populates part of the jest globals into the global space but doesn't add functions like [_createJestObjectFor()](https://github.com/facebook/jest/blob/46c9c13811ca20a887e2826c03852f2ccdebda7a/packages/jest-runtime/src/index.ts#L1814-1900) from jest-runtime. This is why you can use spyOn but not mock - jest-mock actually doesn't declare a mock function until you initialize it with the MockModule.[generateFromMetadata<T, Y extends Array<unknown>>(](https://github.com/facebook/jest/blob/3a85065fe5604655e1337ffc1631f9999722c821/packages/jest-mock/src/index.ts#L826-L839)

@CompuIves you're getting tagged just because you seem to be the only maintainer here. There may be someone better who can answer these questions. Sorry about that!

1. Is there a reason that jest-runtime isn't being used to its full extent here?
2. Why is jest-mock being used as the jest object here? 

I am trying to get a jest-runtime instance set up in the codesandbox world. I presume there might be issues with this - namely the jest-runtime needs some sort of file/module resolver, which may not play nicely with the codesandbox environment.

For everyone who hasn't looked into it - Jest has a lot going on and even I don't completely understand how the Jest runtime works (and its created differently for node/jsdom!).

**Comment by milichev** [comment]
![image](https://user-images.githubusercontent.com/533183/186926192-bf77c665-0efb-471b-acf5-5c164586a152.png)

**Comment by xblue-light** [comment]
Hey guess what .. **jest.mock** is still NOT a function sigh

**Comment by sunny15100** [comment]
Hey guess what .. jest.mock is still NOT a function sigh

**Comment by nickmccurdy** [comment]
I'd recommend switching to cloud sandboxes as they can natively run Node tools (including Jest).
