### ISSUE TITLE
Component tests no longer work.

### ISSUE THREAD

**Issue by cloggy45** [CompuIves/codesandbox-client#866]
# 🐛 bug report

## Description of the problem

When using Enzyme and Jest to run component tests they generate the following message
```

There was an error while evaluating the file:

Could not find module in path: 'object-inspect/util.inspect' relative to '/node_modules/object-inspect/index.js'

ModuleNotFoundError: Could not find module in path: 'object-inspect/util.inspect' relative to '/node_modules/object-inspect/index.js'
    at r (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:331920)
    at new r (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:483740)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:504749)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:505395)
    at d (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:527956)
    at evaluate (https://qv5vl50j1w.codesandbox.io/node_modules/object-inspect/index.js:12:21)
    at ie (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:516511)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528233)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500420)
    at d (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528027)
    at evaluate (https://qv5vl50j1w.codesandbox.io/node_modules/enzyme/build/Debug.js:45:22)
    at ie (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:516511)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528233)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500420)
    at d (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528027)
    at evaluate (https://qv5vl50j1w.codesandbox.io/node_modules/enzyme/build/ReactWrapper.js:31:14)
    at ie (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:516511)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528233)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500420)
    at d (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528027)
    at evaluate (https://qv5vl50j1w.codesandbox.io/node_modules/enzyme/build/index.js:1:199)
    at ie (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:516511)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528233)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500420)
    at d (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528027)
    at evaluate (https://qv5vl50j1w.codesandbox.io/src/containers/Graph.spec.js:11:15)
    at ie (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:516511)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528233)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500420)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500193)
    at e. (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:495398)
    at g (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10482)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10270)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10661)
    at n (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45137)
    at https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45278
    at new Promise ()
    at new t (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:97647)
    at https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45072
    at https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:495707
    at Array.map ()
    at e. (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:495261)
    at g (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10482)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10270)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10661)
    at n (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45137)
    at https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45233
```

## How has this issue affected you? What are you trying to accomplish?

Unable to run component tests.

###  Link to sandbox: [link]() (optional)

[sandbox](https://codesandbox.io/s/qv5vl50j1w)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Latest
| Browser | Version 66.0.3359.181 (Official Build) (64-bit)
| Operating System | Windows 10

**Comment by bosscube** [comment]
I still see this issue using the above sandbox link (https://codesandbox.io/s/qv5vl50j1w)

I also noticed this issue on my own sandbox. Has the issue returned?
