### ISSUE TITLE
Component tests no longer work

### ISSUE THREAD

**Issue by bosscube** [CompuIves/codesandbox-client#936]
# 🐛 bug report

## Description of the problem
**This bug is a regression (#866)**

When using Enzyme and Jest to run component tests they generate the following message:
```
There was an error while evaluating the file:

Could not find module in path: 'object-inspect/util.inspect' relative to '/node_modules/object-inspect/index.js'

ModuleNotFoundError: Could not find module in path: 'object-inspect/util.inspect' relative to '/node_modules/object-inspect/index.js'
    at r (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:331920)
    at new r (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:483740)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:504749)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:505395)
    at d (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:527956)
    at evaluate (https://qv5vl50j1w.codesandbox.io/node_modules/object-inspect/index.js:12:21)
    at ie (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:516511)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528233)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500420)
    at d (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528027)
    at evaluate (https://qv5vl50j1w.codesandbox.io/node_modules/enzyme/build/Debug.js:45:22)
    at ie (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:516511)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528233)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500420)
    at d (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528027)
    at evaluate (https://qv5vl50j1w.codesandbox.io/node_modules/enzyme/build/ReactWrapper.js:31:14)
    at ie (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:516511)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528233)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500420)
    at d (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528027)
    at evaluate (https://qv5vl50j1w.codesandbox.io/node_modules/enzyme/build/index.js:1:199)
    at ie (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:516511)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528233)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500420)
    at d (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528027)
    at evaluate (https://qv5vl50j1w.codesandbox.io/src/containers/Graph.spec.js:11:15)
    at ie (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:516511)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:528233)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500420)
    at e.value (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:500193)
    at e. (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:495398)
    at g (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10482)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10270)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10661)
    at n (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45137)
    at https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45278
    at new Promise ()
    at new t (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:97647)
    at https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45072
    at https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:495707
    at Array.map ()
    at e. (https://codesandbox.io/static/js/sandbox.cccc7eb4.js:259:495261)
    at g (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10482)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10270)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10661)
    at n (https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45137)
    at https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45233
```

## How has this issue affected you? What are you trying to accomplish?
Unable to run component tests.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Latest
| Browser | Chrome 67.0.3396.99 (Official Build) (64-bit)
| Operating System | Windows 10

**Comment by CompuIves** [comment]
Hey! For me this works: 
<img width="1440" alt="screen shot 2018-06-29 at 18 20 05" src="https://user-images.githubusercontent.com/587016/42105656-1a1e6f2e-7bc9-11e8-907b-4c2d61e7f9eb.png">

We did have this problem before though. Could you do a quick check which version you are on? You can find it in the bottom left corner in the sidebar.

**Comment by bosscube** [comment]
Hello! Strange, it worked when I visited that sandbox link again, but when I forked it, it no longer worked.

![image](https://user-images.githubusercontent.com/1063283/42107126-3b5e49fe-7ba4-11e8-8c93-495a501bdf42.png)

Fork is here: https://codesandbox.io/s/2zl12pxvjy

**Comment by bosscube** [comment]
Just realized I didn't grab the update 🤦‍♂️

**Comment by Dremora** [comment]
It seems the issue is still present... occasionally. I had [a sandbox](https://codesandbox.io/s/3rxq4x2oq1) which was broken but resrtarting it a few times has somehow resolved the issue.
