### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by sompylasar** [CompuIves/codesandbox-client#951]
# 🐛 bug report

## Description of the problem

Cannot use `joymap` from a CodeSandbox React app, which seems to also import `babel-polyfill`. The issue does not reproduce in CodeSandbox Vanilla (Parcel) template.

Recommended solution is to not import `babel-polyfill` in library code: https://babeljs.io/docs/en/babel-polyfill/#details so I filed an issue to `joymap`: https://github.com/diegodoumecq/joymap/issues/6

But maybe there's also a solution from the CodeSandbox side which could make using such libraries possible.

------

<img width="1440" alt="screen shot 2018-07-08 at 5 07 43 pm" src="https://user-images.githubusercontent.com/498274/42425380-7b3b207c-82d1-11e8-88d2-a28ba21e4b76.png">

```
Error: only one instance of babel-polyfill is allowed
    at evaluate (https://3xlknpxpnq.codesandbox.io/node_modules/babel-polyfill/lib/index.js:10:9)
    at oe (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:266028)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:277949)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:249394)
    at d (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:277743)
    at evaluate (https://3xlknpxpnq.codesandbox.io/node_modules/joymap/bin/index.js:8:1)
    at oe (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:266028)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:277949)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:249394)
    at d (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:277743)
    at evaluate (https://3xlknpxpnq.codesandbox.io/src/index.js:11:15)
    at oe (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:266028)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:277949)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:249394)
    at e.value (https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:249167)
    at https://codesandbox.io/static/js/sandbox.c7332c5c.js:1:67799
    at g (https://codesandbox.io/static/js/common-sandbox.3b0bd51a.chunk.js:1:156219)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.3b0bd51a.chunk.js:1:156007)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.3b0bd51a.chunk.js:1:156398)
    at n (https://codesandbox.io/static/js/common-sandbox.3b0bd51a.chunk.js:1:169318)
    at https://codesandbox.io/static/js/common-sandbox.3b0bd51a.chunk.js:1:169414
```

Code:
```js
import React from "react";
import ReactDOM from "react-dom";

import { createJoyMap, createQueryModule } from "joymap";

const rootElement = document.getElementById("root");
ReactDOM.render(<div />, rootElement);
```

## How has this issue affected you? What are you trying to accomplish?

Trying to use `joymap` package from `npm` as a dependency.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1530978082-067f9fe
| Browser | Chrome 67 `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36`
| Operating System | macOS 10.12 Sierra

**Comment by sompylasar** [comment]
Closing. Looks like this was fixed somewhere, does not reproduce in the test sandbox https://codesandbox.io/s/3xlknpxpnq 

Possibly related: 
- https://github.com/CompuIves/codesandbox-client/pull/1103 
- https://github.com/CompuIves/codesandbox-client/pull/170
